---
- hosts: development
  tasks:
    - name: create groups
      group: name={{ item.name }}
      with_items: '{{ linux_groups }}'
    - name: add users
      user: name={{ item.name }} groups={{ item.groups }}
      with_items: '{{ users }}'
    - name: package upgrade
      yum: name=* state=latest
    - name: install tmux
      yum: name=tmux state=present
    - name: install yum-utils
      yum: name=yum-utils state=present
    - name: add docker repo
      shell: "yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"
      args:
        chdir: "/etc/yum.repos.d"
        creates: docker-ce.repo
    - name: install docker-ce
      yum: name=docker-ce state=present
    - name: restart docker
      systemd:
        name: docker.service
        state: restarted
        daemon_reload: yes
        enabled: yes
